"""
Database package for the Agentic Business Operating Platform.

Provides database models, connections, and migrations.
"""

from .core import get_db, get_engine, Base, create_db_and_tables
from .models import (
    Base as BaseModel,
    UUIDMixin,
    TimestampMixin,
    TenantIDMixin,
    Organization,
    Workspace,
    BusinessUnit,
    Team,
    User,
    UserRole,
    UserRoleAssignment,
    Integration,
    IntegrationConnection,
    Connector,
    ConnectorConfig,
    SyncStatus,
    DataSource,
    DataSourceType,
    DataSyncLog,
    Document,
    DocumentVersion,
    DocumentCategory,
    KnowledgeBase,
    KnowledgeDocument,
    KnowledgeChunk,
    Agent,
    AgentTool,
    Tool,
    ToolPermission,
    Workflow,
    WorkflowStep,
    Action,
    Approval,
    ActionExecutionLog,
    AuditLog,
    AuditEvent,
    SystemSetting,
    TenantSetting,
    UsageMetric,
    UsageAggregation,
)

__all__ = [
    # Core
    'get_db',
    'get_engine',
    'Base',
    'create_db_and_tables',
    # Models
    'BaseModel',
    'UUIDMixin',
    'TimestampMixin',
    'TenantIDMixin',
    'Organization',
    'Workspace',
    'BusinessUnit',
    'Team',
    'User',
    'UserRole',
    'UserRoleAssignment',
    'Integration',
    'IntegrationConnection',
    'Connector',
    'ConnectorConfig',
    'SyncStatus',
    'DataSource',
    'DataSourceType',
    'DataSyncLog',
    'Document',
    'DocumentVersion',
    'DocumentCategory',
    'KnowledgeBase',
    'KnowledgeDocument',
    'KnowledgeChunk',
    'Agent',
    'AgentTool',
    'Tool',
    'ToolPermission',
    'Workflow',
    'WorkflowStep',
    'Action',
    'Approval',
    'ActionExecutionLog',
    'AuditLog',
    'AuditEvent',
    'SystemSetting',
    'TenantSetting',
    'UsageMetric',
    'UsageAggregation',
]
